---

# AWS Base Config
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
aws_region: "{{ lookup('env','REGION') }}"
ec2_zone: 
ec2_image: 
ec2_instance_type: 
ec2_keypair: 
ec2_security_group: default
ec2_instance_count:

# VPC Config
vpc_cidr_block: ""
vpc_tags:
  vpc_name: ""
  enviroment: ""

# EC2 Config
tikv_instances_types: ""
