---

- name: "NETWORK | CREATE VPC {{ vpc_cidr_block }}"
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    name: "{{ vpc_tags.vpc_name }}"
    state: present
    internet_gateway: True
    resource_tags:
      CreateBy: ansible_aws
      ManagedBy: ansible_aws
      Region: "{{ aws_region }}"
      Enviroment: "{{ vpc_tags.enviroment }}"
  register: vpc
