---

- name: "NETWORK | TERMINATE VPC BY VPC_ID"
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    state: absent
    cidr_block: "{{ vpc_cidr_block }}"
  
