---

- name: "NETWORK | GET VPC INFO FILETER BY CIDR"
  ec2_vpc_net_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      cidr: "{{ vpc_cidr_block }}"
  register: vpc
