---

- name: "NETWORK | CREATE SUBNETS in VPC {{ vpc_id }}"
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    state: present
    cidr: "{{ item.cidr }}"
    az: "{{ ec2_zone }}"
    resource_tags:
      Name: "{{ vpc_name }}_{{ item.type }}"
      CreateBy: ansible_aws
      ManagedBy: ansible_aws
      Region: "{{ aws_region }}"
      Enviroment: "{{ enviroment }}"
      SubnetType: "{{ item.type }}"
  with_items: "{{ subnets_conf }}"
  register: subnets
  when: vpc_id is defined

# - name: "NETWORK | DESCRIPT SUBNETS INFO"
#   debug:
#     msg: "{{ subnets.results }}"

- name: "NETWORK | SET PUBLIC SUBNET ID"
  set_fact:
    public_subnetid: "{{ subnets.results[0].subnet.id }}"

- name: "NETWORK | SET PRIVATE SUBNET ID"
  set_fact:
    private_subnetid: "{{ subnets.results[1].subnet.id }}"




