---
dependencies:
  - role: network/vpc/build_vpc
    tags:
      - build-vpc

  - role: network/vpc/search_vpc
    tags:
      - search-vpc

  - role: network/vpc/terminate_vpc
    tags:
      - terminate-vpc
