---

- name: "EC2 | CREATE SECURITY GROUP FOR {{ vpc_id }}"
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: ssh_public
    description: a ssh EC2 group
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
        group_name: "sg_for_ssh_{{ vpc_id }}"
  register: ssh_sg

- name: "EC2 | DEBUG BASTION SECURITY GROUP"
  debug:
    msg "{{ ssh_sg }}"

# - name: "EC2 | LAUNCH A BASTION EC2"
#   ec2:
#     aws_access_key: "{{ aws_access_key }}"
#     aws_secret_key: "{{ aws_secret_key }}"
#     region: "{{ aws_region }}"

