---

- name: "NETWORK | CREATE VPC {{ vpc_cidr_block }}"
  tags:
    - vpc
  ec2_vpc:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    state: present
    internet_gateway: True
    resource_tags:
      Name: "{{ vpc_tags.vpc_name }}"
      CreateBy: ansible_aws
      ManagedBy: ansible_aws
      Region: "{{ aws_region }}"
      Enviroment: "{{ vpc_tags.enviroment }}"
  register: vpc

- name: "NETWORK | Describe VPC"
  debug:
    msg: "{{ vpc }}"

