---

- name: "NETWORK | CREATE IGW ON VPC {{ vpc_id }}"
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    resource_tags:
      CreateBy: ansible_aws
      ManagedBy: ansible_aws
      Region: "{{ aws_region }}"
      Enviroment: "{{ enviroment }}"
      VPC: "{{ vpc_id }}"
  register: igw

- name: "NETWORK | SET igw_id FOR WHOLE PLAYBOOK"
  set_fact:
    igw_id: "{{ igw.gateway_id }}"

# - name: "NETWORK | DESCRIPT IGW"
#   debug:
#     msg: "{{ igw }}"
